language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "nandakumar82"
    token:
      secure: "b0a881694c1a82857760a55595da3af822e1f652" # encrypted value of your token

script:
  - ./mvnw clean install -B
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nandakumar82_editable_profile_backend