language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "nandakumar82"
    token:
      secure: "b0a881694c1a82857760a55595da3af822e1f652" # encrypted value of your token

script:
  - mvn -N io.takari:maven:wrapper
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nandakumar82_editable_profile_backend

sudo: required

services:
  - docker

before_install:
  - chmod +x mvnw

after_success:
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export IMAGE_NAME=nandakumar82/editable_profile
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: editableprofilebackend